import type { NextApiRequest, NextApiResponse } from "next";

export const foods = [
  {
    id: 1,
    name: "Phở bò",
    type: "món nước",
    price: "trung bình",
    priceRange: "45-60k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["đói bụng", "sợi", "nóng", "truyền thống"],
    description: "Phở bò với nước dùng ngọt thanh, thịt bò mềm",
    image: "pho-bo.jpg",
  },
  {
    id: 2,
    name: "Cơm tấm",
    type: "món khô",
    price: "rẻ",
    priceRange: "30-45k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "đói", "sườn nướng"],
    description: "Cơm với sườn nướng, bì, chả trứng",
    image: "com-tam.jpg",
  },
  {
    id: 3,
    name: "Bún chả",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "thịt nướng", "nước mắm"],
    description: "Bún với thịt lợn nướng và nước chấm đặc trưng",
    image: "bun-cha.jpg",
  },
  {
    id: 4,
    name: "Bánh mì",
    type: "món khô",
    price: "rẻ",
    priceRange: "15-30k",
    time: ["sáng", "trưa", "tối"],
    style: "việt nam",
    tags: ["bánh mì", "nhanh", "tiện lợi"],
    description: "Bánh mì giòn với nhiều loại nhân khác nhau",
    image: "banh-mi.jpg",
  },
  {
    id: 5,
    name: "Gỏi cuốn",
    type: "món khô",
    price: "rẻ",
    priceRange: "30-45k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cuốn", "tươi", "healthy"],
    description: "Cuốn với tôm, thịt, rau sống và bún",
    image: "goi-cuon.jpg",
  },
  {
    id: 6,
    name: "Bún bò Huế",
    type: "món nước",
    price: "trung bình",
    priceRange: "45-60k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["cay", "bò", "bún"],
    description: "Bún bò cay nồng đặc trưng của Huế",
    image: "bun-bo-hue.jpg",
  },
  {
    id: 7,
    name: "Bánh xèo",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["bánh", "giòn", "tôm thịt"],
    description: "Bánh xèo giòn với nhân tôm thịt và rau sống",
    image: "banh-xeo.jpg",
  },
  {
    id: 8,
    name: "Cháo lòng",
    type: "món nước",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["sáng"],
    style: "việt nam",
    tags: ["cháo", "lòng", "ấm bụng"],
    description: "Cháo nóng với các loại lòng heo",
    image: "chao-long.jpg",
  },
  {
    id: 9,
    name: "Bún đậu mắm tôm",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["bún", "đậu", "mắm tôm"],
    description: "Bún với đậu rán và mắm tôm đặc trưng",
    image: "bun-dau-mam-tom.jpg",
  },
  {
    id: 10,
    name: "Hủ tiếu",
    type: "món nước",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["hủ tiếu", "thịt", "tôm"],
    description: "Hủ tiếu với nước dùng trong và nhiều loại thịt",
    image: "hu-tieu.jpg",
  },
  {
    id: 11,
    name: "Bún riêu cua",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bún", "cua", "cà chua"],
    description: "Bún với nước dùng cua và riêu cua thơm ngon",
    image: "bun-rieu-cua.jpg",
  },
  {
    id: 12,
    name: "Bánh cuốn",
    type: "món khô",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["sáng"],
    style: "việt nam",
    tags: ["bánh", "hấp", "nhẹ nhàng"],
    description: "Bánh cuốn mỏng với nhân thịt và nấm",
    image: "banh-cuon.jpg",
  },
  {
    id: 13,
    name: "Cơm gà",
    type: "món khô",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "gà", "đơn giản"],
    description: "Cơm với gà luộc hoặc gà xé phay",
    image: "com-ga.jpg",
  },
  {
    id: 14,
    name: "Mì Quảng",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["mì", "đặc sản", "Quảng Nam"],
    description: "Mì với nước dùng đặc, tôm thịt và bánh tráng",
    image: "mi-quang.jpg",
  },
  {
    id: 15,
    name: "Chả cá Lã Vọng",
    type: "món khô",
    price: "đắt",
    priceRange: "150-200k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cá", "thì là", "Hà Nội"],
    description: "Cá chiên với thì là và hành, ăn kèm bún",
    image: "cha-ca-la-vong.jpg",
  },
  {
    id: 16,
    name: "Bò kho",
    type: "món nước",
    price: "trung bình",
    priceRange: "45-60k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bò", "kho", "bánh mì"],
    description: "Bò kho đậm đà, ăn với bánh mì hoặc hủ tiếu",
    image: "bo-kho.jpg",
  },
  {
    id: 17,
    name: "Cơm niêu",
    type: "món khô",
    price: "trung bình",
    priceRange: "50-70k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "niêu đất", "cháy"],
    description: "Cơm nấu trong niêu đất, có lớp cơm cháy giòn",
    image: "com-nieu.jpg",
  },
  {
    id: 18,
    name: "Canh chua",
    type: "món nước",
    price: "rẻ",
    priceRange: "30-45k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["canh", "chua", "cá"],
    description: "Canh chua với cá, dứa, đậu bắp và rau thơm",
    image: "canh-chua.jpg",
  },
  {
    id: 19,
    name: "Bánh canh",
    type: "món nước",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bánh canh", "bột gạo", "cua"],
    description: "Bánh canh với nước dùng đặc và nhiều loại nhân",
    image: "banh-canh.jpg",
  },
  {
    id: 20,
    name: "Gỏi gà",
    type: "món khô",
    price: "trung bình",
    priceRange: "50-70k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["gỏi", "gà", "rau sống"],
    description: "Gỏi gà trộn với rau sống và nước mắm chua ngọt",
    image: "goi-ga.jpg",
  },
  {
    id: 21,
    name: "Lẩu thái",
    type: "món nước",
    price: "đắt",
    priceRange: "150-250k",
    time: ["tối"],
    style: "thái lan",
    tags: ["lẩu", "cay", "hải sản"],
    description: "Lẩu chua cay kiểu Thái với hải sản và rau",
    image: "lau-thai.jpg",
  },
  {
    id: 22,
    name: "Bún cá",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "cá", "dọc mùng"],
    description: "Bún với cá chiên hoặc nướng, dọc mùng và nước dùng chua ngọt",
    image: "bun-ca.jpg",
  },
  {
    id: 23,
    name: "Cơm rang dưa bò",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm rang", "dưa chua", "bò"],
    description: "Cơm rang với dưa chua và thịt bò xào",
    image: "com-rang-dua-bo.jpg",
  },
  {
    id: 24,
    name: "Bánh bèo",
    type: "món khô",
    price: "rẻ",
    priceRange: "20-35k",
    time: ["sáng", "chiều"],
    style: "việt nam",
    tags: ["bánh", "tôm khô", "Huế"],
    description: "Bánh bèo nhỏ với nhân tôm khô và hành phi",
    image: "banh-beo.jpg",
  },
  {
    id: 25,
    name: "Cháo gà",
    type: "món nước",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["sáng"],
    style: "việt nam",
    tags: ["cháo", "gà", "ấm bụng"],
    description: "Cháo nấu với gà, thêm hành phi và gừng",
    image: "chao-ga.jpg",
  },
  {
    id: 26,
    name: "Nem nướng",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["nem", "nướng", "cuốn"],
    description: "Nem nướng cuốn với bánh tráng và rau sống",
    image: "nem-nuong.jpg",
  },
  {
    id: 27,
    name: "Bún mắm",
    type: "món nước",
    price: "trung bình",
    priceRange: "45-60k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "mắm", "miền Tây"],
    description: "Bún với nước dùng mắm, hải sản và thịt",
    image: "bun-mam.jpg",
  },
  {
    id: 28,
    name: "Cơm cháy chà bông",
    type: "món khô",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["chiều"],
    style: "việt nam",
    tags: ["cơm cháy", "chà bông", "ăn vặt"],
    description: "Cơm cháy giòn phủ chà bông và mayonnaise",
    image: "com-chay-cha-bong.jpg",
  },
  {
    id: 29,
    name: "Bún ốc",
    type: "món nước",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bún", "ốc", "chua cay"],
    description: "Bún với ốc và nước dùng chua cay",
    image: "bun-oc.jpg",
  },
  {
    id: 30,
    name: "Cơm lam",
    type: "món khô",
    price: "rẻ",
    priceRange: "20-35k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "tre", "Tây Bắc"],
    description: "Cơm nếp nấu trong ống tre, thường ăn với gà nướng",
    image: "com-lam.jpg",
  },
  {
    id: 31,
    name: "Mì xào hải sản",
    type: "món khô",
    price: "trung bình",
    priceRange: "50-70k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["mì", "hải sản", "xào"],
    description: "Mì xào với các loại hải sản tươi",
    image: "mi-xao-hai-san.jpg",
  },
  {
    id: 32,
    name: "Cơm gà Hải Nam",
    type: "món khô",
    price: "trung bình",
    priceRange: "45-65k",
    time: ["trưa", "tối"],
    style: "trung hoa",
    tags: ["cơm", "gà", "Hải Nam"],
    description: "Cơm nấu với nước luộc gà, ăn kèm gà luộc",
    image: "com-ga-hai-nam.jpg",
  },
  {
    id: 33,
    name: "Bánh tráng trộn",
    type: "món khô",
    price: "rẻ",
    priceRange: "15-30k",
    time: ["chiều"],
    style: "việt nam",
    tags: ["bánh tráng", "trộn", "ăn vặt"],
    description: "Bánh tráng trộn với đủ loại gia vị và phụ gia",
    image: "banh-trang-tron.jpg",
  },
  {
    id: 34,
    name: "Cháo vịt",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["tối"],
    style: "việt nam",
    tags: ["cháo", "vịt", "gừng"],
    description: "Cháo nấu với vịt, ăn kèm gừng và hành phi",
    image: "chao-vit.jpg",
  },
  {
    id: 35,
    name: "Bún thịt nướng",
    type: "món khô",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "thịt nướng", "nem"],
    description: "Bún với thịt heo nướng, nem, rau sống và nước mắm",
    image: "bun-thit-nuong.jpg",
  },
  {
    id: 36,
    name: "Cơm chiên dương châu",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "trung hoa",
    tags: ["cơm chiên", "xúc xích", "trứng"],
    description: "Cơm chiên với xúc xích, trứng, đậu Hà Lan và các loại rau củ",
    image: "com-chien-duong-chau.jpg",
  },
  {
    id: 37,
    name: "Bánh đa cua",
    type: "món nước",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bánh đa", "cua", "Hải Phòng"],
    description: "Bánh đa với nước dùng cua đặc trưng Hải Phòng",
    image: "banh-da-cua.jpg",
  },
  {
    id: 38,
    name: "Gà nướng",
    type: "món khô",
    price: "đắt",
    priceRange: "150-200k",
    time: ["tối"],
    style: "việt nam",
    tags: ["gà", "nướng", "bia"],
    description: "Gà nướng nguyên con hoặc từng phần, ăn kèm muối ớt",
    image: "ga-nuong.jpg",
  },
  {
    id: 39,
    name: "Súp cua",
    type: "món nước",
    price: "trung bình",
    priceRange: "30-50k",
    time: ["tối"],
    style: "việt nam",
    tags: ["súp", "cua", "trứng"],
    description: "Súp cua đặc với thịt cua và trứng",
    image: "sup-cua.jpg",
  },
  {
    id: 40,
    name: "Bánh mì chảo",
    type: "món khô",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["sáng"],
    style: "việt nam",
    tags: ["bánh mì", "trứng", "pate"],
    description:
      "Bánh mì nướng giòn ăn kèm với trứng, pate và các loại topping",
    image: "banh-mi-chao.jpg",
  },
  {
    id: 41,
    name: "Lẩu cá kèo",
    type: "món nước",
    price: "đắt",
    priceRange: "200-300k",
    time: ["tối"],
    style: "việt nam",
    tags: ["lẩu", "cá kèo", "miền Tây"],
    description: "Lẩu nấu với cá kèo, rau đắng và các loại rau khác",
    image: "lau-ca-keo.jpg",
  },
  {
    id: 42,
    name: "Xôi xéo",
    type: "món khô",
    price: "rẻ",
    priceRange: "15-30k",
    time: ["sáng"],
    style: "việt nam",
    tags: ["xôi", "đậu xanh", "hành phi"],
    description: "Xôi nếp với đậu xanh xay nhuyễn và hành phi",
    image: "xoi-xeo.jpg",
  },
  {
    id: 43,
    name: "Bún sườn chua",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "sườn", "chua"],
    description: "Bún với nước dùng chua ngọt và sườn non",
    image: "bun-suon-chua.jpg",
  },
  {
    id: 44,
    name: "Cơm sườn",
    type: "món khô",
    price: "rẻ",
    priceRange: "30-45k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "sườn", "đơn giản"],
    description: "Cơm với sườn nướng hoặc ram, ăn kèm dưa chua",
    image: "com-suon.jpg",
  },
  {
    id: 45,
    name: "Bánh căn",
    type: "món khô",
    price: "rẻ",
    priceRange: "20-35k",
    time: ["sáng", "chiều"],
    style: "việt nam",
    tags: ["bánh", "bột gạo", "Đà Lạt"],
    description: "Bánh nhỏ làm từ bột gạo, ăn kèm với nước mắm pha",
    image: "banh-can.jpg",
  },
  {
    id: 46,
    name: "Cá kho tộ",
    type: "món khô",
    price: "trung bình",
    priceRange: "50-70k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cá", "kho", "tộ đất"],
    description: "Cá kho trong tộ đất với nước mắm và thịt ba chỉ",
    image: "ca-kho-to.jpg",
  },
  {
    id: 47,
    name: "Bún mọc",
    type: "món nước",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bún", "mọc", "sườn"],
    description: "Bún với nước dùng trong và các loại mọc, sườn",
    image: "bun-moc.jpg",
  },
  {
    id: 48,
    name: "Cơm cháy kho quẹt",
    type: "món khô",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["chiều"],
    style: "việt nam",
    tags: ["cơm cháy", "kho quẹt", "ăn vặt"],
    description: "Cơm cháy giòn ăn với nước kho quẹt đậm đà",
    image: "com-chay-kho-quet.jpg",
  },
  {
    id: 49,
    name: "Bún ốc nguội",
    type: "món khô",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["bún", "ốc", "Hà Nội"],
    description: "Bún trộn với ốc luộc và nước mắm chua ngọt",
    image: "bun-oc-nguoi.jpg",
  },
  {
    id: 50,
    name: "Cơm hến",
    type: "món khô",
    price: "rẻ",
    priceRange: "25-40k",
    time: ["trưa"],
    style: "việt nam",
    tags: ["cơm", "hến", "Huế"],
    description: "Cơm trộn với hến, rau sống và nước mắm",
    image: "com-hen.jpg",
  },
  {
    id: 51,
    name: "Phở gà",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-55k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["phở", "gà", "truyền thống"],
    description: "Phở với nước dùng gà và thịt gà",
    image: "pho-ga.jpg",
  },
  {
    id: 52,
    name: "Bánh khọt",
    type: "món khô",
    price: "rẻ",
    priceRange: "30-45k",
    time: ["chiều"],
    style: "việt nam",
    tags: ["bánh", "tôm", "Vũng Tàu"],
    description: "Bánh nhỏ giòn với nhân tôm, ăn kèm rau sống",
    image: "banh-khot.jpg",
  },
  {
    id: 53,
    name: "Cháo trai",
    type: "món nước",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["tối"],
    style: "việt nam",
    tags: ["cháo", "trai", "gừng"],
    description: "Cháo nấu với thịt trai và gừng",
    image: "chao-trai.jpg",
  },
  {
    id: 54,
    name: "Bún đậu mắm tôm",
    type: "món khô",
    price: "trung bình",
    priceRange: "40-60k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["bún", "đậu", "mắm tôm"],
    description: "Bún ăn kèm đậu hũ chiên, chả cốm và mắm tôm",
    image: "bun-dau-mam-tom.jpg",
  },
  {
    id: 55,
    name: "Cơm gà xối mỡ",
    type: "món khô",
    price: "trung bình",
    priceRange: "45-65k",
    time: ["trưa", "tối"],
    style: "việt nam",
    tags: ["cơm", "gà", "xối mỡ"],
    description: "Cơm với gà chiên giòn xối mỡ",
    image: "com-ga-xoi-mo.jpg",
  },
  {
    id: 56,
    name: "Bánh ướt thịt nướng",
    type: "món khô",
    price: "trung bình",
    priceRange: "35-50k",
    time: ["sáng", "trưa"],
    style: "việt nam",
    tags: ["bánh ướt", "thịt nướng", "Đà Lạt"],
    description: "Bánh ướt mỏng ăn kèm thịt nướng và nước mắm",
    image: "banh-uot-thit-nuong.jpg",
  },
];
export const normalize = (text: string) => {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
};

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).json({ message: "Method not allowed" });
  }

  const randomFood = foods[Math.floor(Math.random() * foods.length)];
  res.status(200).json(randomFood.name);
}
